### ISSUE TITLE
Error Downloading

### ISSUE THREAD

**Issue by fis60** [K0ng2/bilisubdl#1]
Hello thanks for the script, i believe https://bilibili.tv/ made a change to the subtitle api which in turn broke the download.

**Comment by K0ng2** [comment]
fixed [new release](https://github.com/K0ng2/bilisubdl/releases/tag/v1.1.6) (https://github.com/K0ng2/bilisubdl/commit/e65449288f0cd5c50d6e54aec6534eb67d531317)
