### ISSUE TITLE
How do i get [id], I tried the url but it didn't work

### ISSUE THREAD

**Issue by alethinh** [K0ng2/bilisubdl#2]
How do i get [id], I tried the url but it didn't work

**Comment by K0ng2** [comment]
ID is in url

# example

url = `https://www.bilibili.tv/en/play/1064876?bstar_from=bstar-web.homepage.anime.all`

to download in English

`bilisubdl 1064876 -l en`

**Comment by alethinh** [comment]
Thank you, i guess it works only on bilibli.tv and i try on space.bilibili.com it doesnt work
